# =====================================================================
# Configuration globale partagée par tous les microservices
# Projet : gestion-etudiant (UASZ)
# Repository : gestion-etudiant-config
# =====================================================================

spring:
  application:
    name: global-config

  cloud:
    config:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: false  # Désactive la découverte automatique des routes

# Configuration globale des logs
logging:
  level:
    root: INFO
    org.springframework: INFO

# Gestion des erreurs serveur
server:
  error:
    include-message: always
    include-binding-errors: always

# Actuator accessible pour tous les microservices
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always